# Generated by Django 5.0.2 on 2024-10-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_bedroom_property_bedrooms_property_favorited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorited',
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
